spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qing1016..
    url: jdbc:mysql://47.94.238.122/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    port: 6379
    host: localhost

server:
  context-path: /sell


wechat:
  mpAppId: hjk187fdsb3
  mpAppSecret: fds1341234hdjfs